### PR TITLE
Update bundler config for surge demo 

### PR DESCRIPTION
**Pull request by fajar-apri-alaska**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #115 

## Summary:
- adding auro-icon check-lg to rollup bundled files
- update index.html to import from bundled files
- update `npm run dev` script to run `bundler` script also.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [x] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by jason-capsule42 — CHANGES_REQUESTED** [review]
This PR is creating a surge demo that doesn't work.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
I have multiple concerns about this solution. I will need more time to understand what is happening here and support with a clear direction for updates.

**Comment by blackfalcon** [comment]
Moving this PR to DRAFT. Please DO NOT release this update until I have finished a review.

**Comment by blackfalcon** [comment]
See resolving PR: https://github.com/AlaskaAirlines/auro-checkbox/pull/131

**Pull request closed without merging**
